# Generated by Django 5.2.1 on 2025-07-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_view_events', 'Can view events'), ('can_register_himself', 'Can register himself'), ('can_unregister_himself', 'Can unregister himself'), ('can_view_own_registrations', 'Can view own registrations'), ('can_create_event', 'Can create event'), ('can_edit_own_event', 'Can edit own event'), ('can_delete_own_event', 'Can delete own event'), ('can_view_own_event_registrations', 'Can view own event registrations'))},
        ),
    ]
